Text('Country: ${vehicle.country}'),
Text('Plate: ${vehicle.plate}'),
Text('EU: ${vehicle.euGroup} / ${vehicle.euSubcategory}'),
Text('Fuel: ${vehicle.fuelType}'),
Text('Emission: ${vehicle.emissionStandard}'),
Text('Has trailer: ${vehicle.hasTrailer ? "Yes" : "No"}'),
Text('Axles: ${vehicle.axles ?? "-"}'),
Text('GVW (kg): ${vehicle.gvwKg ?? "-"}'),
